language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "akshya1997"
    token: $SONARQUBE_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=akshya-engineering-stream-2020_thoven-api

before_install:
  - chmod +x mvnw
